Adds Elasticsearch / X-Pack configuration via Env variables.
UKHomeOffice/docker-kibana pull request #5
Opened 2017-06-05 14:25 UTC by marcinc

2017-06-05 16:06 UTC, vaijab requested changes

2017-06-05 16:06 UTC, vaijab commented on kibana.yml
> +%ELASTICSEARCH_USERNAME%
Should this read `elasticsearch.username: %ELASTICSEARCH_USERNAME%` ?

2017-06-05 16:06 UTC, vaijab commented on run.sh
> +: ${XPACK_SECURITY_ENCRYPTION_KEY:=$(uuidgen)}
Is it OK to regen this every time kibana runs?

2017-06-05 17:41 UTC, marcinc commented on run.sh
> +: ${XPACK_SECURITY_ENCRYPTION_KEY:=$(uuidgen)}
Yes. It's an arbitrary string of 32 characters or more used to encrypt credentials in a cookie. If it changes the worse that can happen is that user will be asked to sign in again.

2017-06-05 17:43 UTC, marcinc commented on kibana.yml
> +%ELASTICSEARCH_USERNAME%
This is a bit ugly I agree but with default empty values for both username and password this seem to break configuration. The workaround for that it to include entire line only if username / password is specified.

2017-06-06 09:21 UTC, jits approved these changes
One minor thing, otherwise LG.

2017-06-06 09:21 UTC, jits commented on kibana.yml
> +%ELASTICSEARCH_USERNAME%
Should probably use a different name then, given the user specified env var is also called `ELASTICSEARCH_USERNAME`?

2017-06-06 10:40 UTC, marcinc commented on kibana.yml
> +%ELASTICSEARCH_USERNAME%
@jits This is our convention. `ELASTICSEARCH_USERNAME` env variable replaces a placeholder of the same name `%ELASTICSEARCH_USERNAME%`.

2017-06-06 10:42 UTC, jits commented on kibana.yml
> +%ELASTICSEARCH_USERNAME%
But in this case you're not directly replacing the placeholder `%ELASTICSEARCH_USERNAME%` with the value of the env var `ELASTICSEARCH_USERNAME` – you're deriving a new output from the original env var which gets put here, as Vaidas pointed out above.

2017-06-06 10:42 UTC, jits commented on kibana.yml
> +%ELASTICSEARCH_USERNAME%
(General point being it could be clearer when someone looks at it in a few months time :D)

2017-06-06 10:58 UTC, marcinc commented on kibana.yml
> +%ELASTICSEARCH_USERNAME%
Yes, in this case if env var is specified it'll basically add entire config line with it's value placed there. I can change the placeholder name if that helps?

2017-06-06 11:22 UTC, marcinc commented
@jits Changed the placeholder names. Hope that's more clear now?

2017-06-06 11:23 UTC, jits commented
@marcinc – looks great to me!

2017-06-06 13:28 UTC, vaijab commented on run.sh
> +: ${XPACK_SECURITY_ENCRYPTION_KEY:=$(uuidgen)}
How does it work when there is more than one pod and a user hits different pod each request?

2017-06-06 13:40 UTC, marcinc commented on run.sh
> +: ${XPACK_SECURITY_ENCRYPTION_KEY:=$(uuidgen)}
@vaijab One can always pass a fixed value in environment to ensure all instances use the same encryption key.

2017-06-06 13:49 UTC, vaijab approved these changes

2017-06-06 14:18 UTC, merged